markdown: GFM

plugins:
  - jekyll-remote-theme

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

nagivation:
  - name: Overview
    link: ./README.html
  - name: Getting Started
    link: ./Getting-Started.html
  

sidebar:
  - getting-started
  - label: Building and Testing the Robot
    children:
      - part-fabrication
      - robot-assembly
      - software-setup
  - label: Software Documentation
    children:
      - software-architecture
      - behavior-guide
      - comm-protocol
  - label: Hardware Documentation
    children:
      - angle-ranges
