markdown: GFM

plugins:
  - jekyll-remote-theme

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

nagivation:
  - name: System Overview
    link: ./
  - name: Getting Started
    link: ./Getting-Started.html
  - name: Part Fabrication
    link: ./component-fabrication.html
  - name: Robot Assembly
    link: ./Robot-Assembly.html
    sublist:
      - name: Electronics Setup
        link: ./Robot-Assembly.html#setting-up-the-control-board
      - name: Servo Initialization
        link: ./Robot-Assembly.html#initializing-servo-ids-and-positions
  
